/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

export interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/list/list" |
       "/pages/pageList/pageList" |
       "/pages/pull-down/pull-down" |
       "/pages/user/user" |
       "/pages/work/work" |
       "/pages-sub/demo/demo";
}
interface RedirectToOptions extends NavigateToOptions {}

export interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/user/user"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
